### PR TITLE
[[FIX]] change escape-sequence handler for double quotes (\")

### LINKED ISSUE #3315: `"` and `\"` are considered as different keys
JsHint version: 2.9.6

Code:
```
var x = {
  '"': 10,
  '\"': 20,
};
```

Configuration: default

Result: no warnings

Expected result: W075: Duplicate key

### PR DESCRIPTION
**Pull request by maayami**
Changes the handling of escape sequence case for `\"` in the **lex.js** file. Earlier, it converted `\"` into `\\\"`, which is not the correct js equivalent for the case as it should be `"` only. This was causing issue #3315 as `\" != "` that is why jshint considers them different strings.

Fixes and Closes #3315

### CODE REVIEW

File: src/lex.js [hunk 1]
```diff
@@ -1115,7 +1115,6 @@ Lexer.prototype = {
       char = "\\\\";
       break;
     case "\"":
-      char = "\\\"";
```
Comment (jugglinmike) [inline src/lex.js:1118]: Since this "case" clause no longer has any purpose, we can remove it entirely.

**Review by jugglinmike — CHANGES_REQUESTED** [review]
Thanks for the patch! Could you add a unit test which demonstrates its correctness? The file `tests/unit/core.js` seems like a good place for this. We could use a test case that fails in the current release of JSHint but passes with this patch applied. That will prove that this patch has the intended effect, and it will help us avoid accidentally breaking the new and improved behavior in the future.

**Comment by maayami** [comment]
Sure @jugglinmike  I'll add a unit test for this.
Also, could you please help me in running the jshint clone on the local development server.

File: src/lex.js (hunk 1 above)
Comment (maayami) [reply src/lex.js:1118]: Okay will do that and will also check for any breaking changes after that.

**Comment by maayami** [comment]
Hey @jugglinmike, I have added a unit test in the commit `849e08d` that fails for the latest version of JSHint but passes with this path applied.

File: src/lex.js (hunk 1 above)
Comment (maayami) [reply src/lex.js:1118]: Done, I have made the changes suggested by you in the commit `
cf99223 `.

**Review by jugglinmike — APPROVED** [review]

**Comment by jugglinmike** [comment]
Beautiful! Thanks for the help!
